name: Run Benchmarks

permissions:
  id-token: write
  contents: write
  deployments: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build benchmark parser
        run: npm run build -w benchmark-parser

      - name: Create Appium Test Zip
        run: npm run bundle -w benchmarking-scripts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEVICE_FARM_IAM_ARN }}
          aws-region: us-west-2

      - name: Run Benchmark with JavaScriptCore Engine
        id: run-jsc-benchmark
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.3
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "TestApp",
              "appArn": "jscBenchmarking.ipa",
              "devicePoolArn": "SmallDevicePool",
              "executionConfiguration": {
                "jobTimeoutMinutes": 20
              },
              "test": {
                "type": "APPIUM_NODE",
                "testPackageArn": "packages/benchmarking/MyTests.zip",
                "testSpecArn": "packages/benchmarking/testSpec.yaml"
              }
            }
          artifact-types: ALL

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: JSCOutputFiles
          path: ${{ steps.run-jsc-benchmark.outputs.artifact-folder }}

      - name: Extract JSC Artifacts
        run: |
          ./scripts/unzipArchive.sh ${{ steps.run-jsc-benchmark.outputs.artifact-folder }} benchmarks/jsc

      - name: Run Benchmark with Hermes Engine
        id: run-hermes-benchmark
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.3
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "TestApp",
              "appArn": "hermesBenchmarking.ipa",
              "devicePoolArn": "SmallDevicePool",
              "executionConfiguration": {
                "jobTimeoutMinutes": 20
              },
              "test": {
                "type": "APPIUM_NODE",
                "testPackageArn": "packages/benchmarking/MyTests.zip",
                "testSpecArn": "packages/benchmarking/testSpec.yaml"
              }
            }
          artifact-types: ALL

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: HermesOutputFiles
          path: ${{ steps.run-hermes-benchmark.outputs.artifact-folder }}

      - name: Extract Hermes Artifacts
        run: |
          ./scripts/unzipArchive.sh ${{ steps.run-hermes-benchmark.outputs.artifact-folder }} benchmarks/hermes

      - name: Parse Benchmarks
        run: npm run parse-benchmarks

      - name: Report Benchmarks
        run: cat benchmark.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "React Native Benchmarks"
          tool: "customSmallerIsBetter"
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
