name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run lint -w benchmarking-test-app

      - name: Run benchmark parser tests
        run: npm test -w benchmark-parser

      - name: Validate JavaScript build
        run: |
          cd apps/benchmarking-test-app
          npm install
          npm run build:ios:release
